version: "2"

services:
  server:
    env_file:
      - .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - 3000:3000
    command: python src/server.py

  dbdata:
    image: busybox
    volumes:
      - /var/lib/mysql

  db:
    env_file:
      - .env
    image: mysql:8.0.19
    ports:
      - 3306:3306
    volumes_from:
      - dbdata
    restart: always
