version: "2"

services:
  server:
    env_file:
      - .env
    build: ./docker/
    working_dir: /mnt
    restart: always
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - 80:3000
    command: python src/server.py

  dbdata:
    image: busybox
    volumes:
      - /var/lib/mysql

  db:
    env_file:
      - .env
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes_from:
      - dbdata
    restart: always
