wso2.carbon:
  id: siddhi-runner
  name: Siddhi Runner Distribution
  ports:
    offset: 0
transports:
  http:
    listenerConfigurations:
    - id: default
      host: 0.0.0.0
      port: 9090
    - id: msf4j-https
      host: 0.0.0.0
      port: 9443
      scheme: https
      sslConfig:
        keyStore: ${carbon.home}/resources/security/wso2carbon.jks
        keyStorePass: wso2carbon
        certPass: wso2carbon
    transportProperties:
    - name: server.bootstrap.socket.timeout
      value: 60
    - name: client.bootstrap.socket.timeout
      value: 60
    - name: latency.metrics.enabled
      value: true
dataSources:
- name: WSO2_CARBON_DB
  description: The datasource used for registry and user manager
  definition:
    type: RDBMS
    configuration:
      jdbcUrl: jdbc:h2:${sys:carbon.home}/wso2/${sys:wso2.runtime}/database/WSO2_CARBON_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
      username: wso2carbon
      password: wso2carbon
      driverClassName: org.h2.Driver
      maxPoolSize: 10
      idleTimeout: 60000
      connectionTestQuery: SELECT 1
      validationTimeout: 30000
      isAutoCommit: false
