"""empty message

Revision ID: 3b7d9016fa35
Revises: 7f5ce6aec65e
Create Date: 2020-04-25 22:36:23.646576

"""

# revision identifiers, used by Alembic.
revision = '3b7d9016fa35'
down_revision = '7f5ce6aec65e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zip_alert', 'current_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zip_alert', sa.Column('current_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
