"""empty message

Revision ID: 408ed9c055d1
Revises: 8e6fa85ecb84
Create Date: 2020-04-26 19:38:17.365997

"""

# revision identifiers, used by Alembic.
revision = '408ed9c055d1'
down_revision = '8e6fa85ecb84'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_data', 'location_code',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=9),
               existing_nullable=True)
    op.drop_column('patient_data', 'is_positive')
    op.alter_column('zip_alert', 'on_alert',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zip_alert', 'on_alert',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('patient_data', sa.Column('is_positive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('patient_data', 'location_code',
               existing_type=sa.String(length=9),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
