"""empty message

Revision ID: 4e1aecb3c6bc
Revises: 905de70ad978
Create Date: 2020-04-22 22:45:17.739402

"""

# revision identifiers, used by Alembic.
revision = '4e1aecb3c6bc'
down_revision = '905de70ad978'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
