"""empty message

Revision ID: 5295b51588c6
Revises: 6123ff92612c
Create Date: 2020-04-22 15:03:33.691674

"""

# revision identifiers, used by Alembic.
revision = '5295b51588c6'
down_revision = '6123ff92612c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
