"""empty message

Revision ID: 6123ff92612c
Revises: b4e60f1a141b
Create Date: 2020-04-17 20:45:50.476327

"""

# revision identifiers, used by Alembic.
revision = '6123ff92612c'
down_revision = 'b4e60f1a141b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zipcode_distance',
    sa.Column('zip_to', sa.String(length=5), nullable=False),
    sa.Column('zip_from', sa.String(length=5), nullable=False),
    sa.Column('distance', sa.Numeric(precision=20, scale=15), nullable=True),
    sa.PrimaryKeyConstraint('zip_to', 'zip_from')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zipcode_distance')
    # ### end Alembic commands ###
