"""empty message

Revision ID: 73476c165ed4
Revises: b4e60f1a141b
Create Date: 2020-04-23 22:00:08.691975

"""

# revision identifiers, used by Alembic.
revision = '73476c165ed4'
down_revision = 'b4e60f1a141b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_data',
    sa.Column('hospital_id', sa.String(length=9), nullable=False),
    sa.Column('hospital_zip', sa.String(length=5), nullable=True),
    sa.Column('beds_total', sa.Integer(), nullable=True),
    sa.Column('beds_occupied', sa.Integer(), nullable=True),
    sa.Column('beds_available', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('zipcode_distance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_to', sa.String(length=5), nullable=True),
    sa.Column('zip_from', sa.String(length=5), nullable=True),
    sa.Column('distance', sa.Numeric(precision=20, scale=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zipcode_distance')
    op.drop_table('hospital_data')
    # ### end Alembic commands ###
