"""empty message

Revision ID: 7f5ce6aec65e
Revises: ce825897feec
Create Date: 2020-04-25 21:28:49.265139

"""

# revision identifiers, used by Alembic.
revision = '7f5ce6aec65e'
down_revision = 'ce825897feec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip_alert',
    sa.Column('zipcode', sa.String(length=5), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=True),
    sa.Column('on_alert', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('zipcode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zip_alert')
    # ### end Alembic commands ###
