"""empty message

Revision ID: 8e6fa85ecb84
Revises: 9267fae76810
Create Date: 2020-04-25 23:08:57.708988

"""

# revision identifiers, used by Alembic.
revision = '8e6fa85ecb84'
down_revision = '9267fae76810'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_data', 'is_positive',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('patient_data', 'mrn',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('zip_alert', 'on_alert',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zip_alert', 'on_alert',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('patient_data', 'mrn',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER())
    op.alter_column('patient_data', 'is_positive',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
