"""empty message

Revision ID: 905de70ad978
Revises: 696c43961598
Create Date: 2020-04-22 22:33:52.576160

"""

# revision identifiers, used by Alembic.
revision = '905de70ad978'
down_revision = '696c43961598'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_data', sa.Column('beds_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital_data', 'beds_total')
    # ### end Alembic commands ###
