"""empty message

Revision ID: aa45845ac437
Revises: dc4d14a493dd
Create Date: 2020-04-22 23:14:48.675981

"""

# revision identifiers, used by Alembic.
revision = 'aa45845ac437'
down_revision = 'dc4d14a493dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_data',
    sa.Column('hospital_id', sa.String(length=9), nullable=False),
    sa.Column('hospital_zip', sa.String(length=5), nullable=True),
    sa.Column('beds_total', sa.Integer(), nullable=True),
    sa.Column('beds_occupied', sa.Integer(), nullable=True),
    sa.Column('beds_available', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('hospital_id')
    )
    op.create_table('zipcode_distance',
    sa.Column('zip_to', sa.String(length=5), nullable=False),
    sa.Column('zip_from', sa.String(length=5), nullable=True),
    sa.Column('distance', sa.Numeric(precision=20, scale=15), nullable=True),
    sa.PrimaryKeyConstraint('zip_to')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zipcode_distance')
    op.drop_table('hospital_data')
    # ### end Alembic commands ###
