"""empty message

Revision ID: b4536c0554a9
Revises: 408ed9c055d1
Create Date: 2020-04-26 19:41:26.264438

"""

# revision identifiers, used by Alembic.
revision = 'b4536c0554a9'
down_revision = '408ed9c055d1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_data', sa.Column('is_positive', sa.Integer(), nullable=True))
    op.alter_column('zip_alert', 'on_alert',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zip_alert', 'on_alert',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('patient_data', 'is_positive')
    # ### end Alembic commands ###
