"""empty message

Revision ID: ce825897feec
Revises: 73476c165ed4
Create Date: 2020-04-24 20:01:30.535864

"""

# revision identifiers, used by Alembic.
revision = 'ce825897feec'
down_revision = '73476c165ed4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_data',
    sa.Column('mrn', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.Integer(), nullable=True),
    sa.Column('is_positive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('mrn')
    )
    op.add_column('hospital_data', sa.Column('trauma_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital_data', 'trauma_level')
    op.drop_table('patient_data')
    # ### end Alembic commands ###
