"""empty message

Revision ID: dc4d14a493dd
Revises: 4e1aecb3c6bc
Create Date: 2020-04-22 23:05:24.432201

"""

# revision identifiers, used by Alembic.
revision = 'dc4d14a493dd'
down_revision = '4e1aecb3c6bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
