dataSources:
  - name: DATABASE
    description: The datasource used for test database
    jndiConfig:
      name: jdbc/database
    definition:
      type: RDBMS
      configuration:
        jdbcUrl: "jdbc:mysql://sam246.cs.uky.edu:3306/database?useSSL=false"
        username: "root"
        password: "password"
        driverClassName: com.mysql.jdbc.Driver
        maxPoolSize: 50
        idleTimeout: 60000
        connectionTestQuery: SELECT 1
        validationTimeout: 30000
        isAutoCommit: false
# This is the main configuration for metrics
metrics:
  # Enable Metrics
  enabled: true
  reporting:
    console:
      - # The name for the Console Reporter
        name: Console
        # Enable Console Reporter
        enabled: true
        # Polling Period in seconds.
        # This is the period for polling metrics from the metric registry and printing in the console
        pollingPeriod: 360
extensions:
  - extension:
      name: query
      namespace: rdbms
      properties:
        perform.CUD.operations: true
